from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    question: str = Field(
        ..., description="Technical question to query against MLIR RAG system"
    )


class AskResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer generated by the assistant")
    sources: list[str] = Field(
        default_factory=list, description="Source document filenames cited"
    )
    context_docs: list[str] = Field(
        default_factory=list, description="Raw context snippets used"
    )
